name: CISD
on: 
  workflow_dispatch:
    inputs:
      prompt:
        required: true
        type: string
      output:
        required: true
        type: string

jobs:
  generation_1:
    #runs-on: pppoe/dev:cisd
    runs-on: ubuntu-latest
    steps:
      - run: 
      - run: touch ${{ inputs.output }}_1.png
      #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}_1.png
      #- run: ls -lh ${{ inputs.output }}_1.png
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.output }}_1.png
          path: ${{ inputs.output }}_1.png
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.output }}_1.png
          path: outputs/${{ inputs.output }}/1.png

  #generation_1:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_1.png
        #- run: ls -lh outputs/${{ inputs.output }}_1.png
  #generation_2:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_2.png
        #- run: ls -lh outputs/${{ inputs.output }}_2.png
  #generation_3:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_3.png
        #- run: ls -lh outputs/${{ inputs.output }}_3.png
  #generation_4:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_4.png
        #- run: ls -lh outputs/${{ inputs.output }}_4.png
  #generation_5:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_5.png
        #- run: ls -lh outputs/${{ inputs.output }}_5.png
  #generation_6:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_6.png
        #- run: ls -lh outputs/${{ inputs.output }}_6.png
  #generation_7:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_7.png
        #- run: ls -lh outputs/${{ inputs.output }}_7.png
  #generation_8:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_8.png
        #- run: ls -lh outputs/${{ inputs.output }}_8.png
  #generation_9:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_9.png
        #- run: ls -lh outputs/${{ inputs.output }}_9.png
  #generation_10:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_10.png
        #- run: ls -lh outputs/${{ inputs.output }}_10.png
  #generation_11:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_11.png
        #- run: ls -lh outputs/${{ inputs.output }}_11.png
  #generation_12:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_12.png
        #- run: ls -lh outputs/${{ inputs.output }}_12.png
  #generation_13:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_13.png
        #- run: ls -lh outputs/${{ inputs.output }}_13.png
  #generation_14:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_14.png
        #- run: ls -lh outputs/${{ inputs.output }}_14.png
  #generation_15:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_15.png
        #- run: ls -lh outputs/${{ inputs.output }}_15.png
  #generation_16:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_16.png
        #- run: ls -lh outputs/${{ inputs.output }}_16.png
  #generation_17:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_17.png
        #- run: ls -lh outputs/${{ inputs.output }}_17.png
  #generation_18:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_18.png
        #- run: ls -lh outputs/${{ inputs.output }}_18.png
  #generation_19:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_19.png
        #- run: ls -lh outputs/${{ inputs.output }}_19.png
  #generation_20:
    #runs-on: pppoe/dev:cisd
      #steps:
        #- run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
        #- run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_20.png
        #- run: ls -lh outputs/${{ inputs.output }}_20.png
