name: CISD
on: 
  workflow_dispatch:
    inputs:
      prompt:
        required: true
        type: string
      output:
        required: true
        type: string

jobs:
  generation_1:
    runs-on: ubuntu-latest
    container:
      image: pppoe/dev:cisd
    steps:
      - uses: actions/checkout@v3
      - run: cd $GITHUB_WORKSPACE && python3 main.py --prompt "${{ inputs.prompt }}" --output ${{ inputs.output }}_1.png
      - run: ls -lh ${{ inputs.output }}_1.png
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.output }}_1.png
          path: ${{ inputs.output }}_1.png
