name: CISD
on: 
  sd_image_generation:
    inputs:
      prompt:
        required: true
        type: string
      output:
        required: true
        type: string

jobs:
  generation_1:
    runs-on: pppoe/dev:cisd
    steps:
      - run: python3 main.py --prompt ${{ inputs.prompt }} --output ${{ inputs.output }}
      - run: cp ${{ inputs.output }}.png outputs/${{ inputs.output }}_1.png
      - run: ls -lh outputs/${{ inputs.output }}_1.png

          #- uses: actions/upload-artifact@v4
          #with:
          #name: my-artifact
          #path: outputs/${{ github.run_id }}/
